### ISSUE TITLE
Languages loading for nodejs not working

### ISSUE THREAD

**Issue by PaGury** [BenjaminVanRyseghem/numbro#108]
The language.js file in dist folder not loading properly all languages. (the last call for the zh-CN locale erase all previous call).

**Comment by BenjaminVanRyseghem** [comment]
works well [here](http://numbrojs.com/try-me.html?lang=fr-FR&value=1234&format=0.00%24)

can you explain more about your use case?

**Comment by BenjaminVanRyseghem** [comment]
(it looks like there is an issue with 'he-IL' though)

**Comment by PaGury** [comment]
It's a nodejs/browserify issue : 
If you look here : 
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = language;
    }

The exported module is erased for each call (so each language erase the previous in the module.exports).

**Comment by BenjaminVanRyseghem** [comment]
It was fixed [there](https://github.com/foretagsplatsen/numbro/pull/101), but not yet released :smile:

**Comment by BenjaminVanRyseghem** [comment]
can you test with this code and tell me?

**Comment by PaGury** [comment]
Nope, not working, the language.js file still not loading properly all languages.
The languages.js file is a merge of all languages files, it's the main problem here.

**Comment by BenjaminVanRyseghem** [comment]
you should use [`loadLanguagesInNode `](https://github.com/foretagsplatsen/numbro/pull/101/files#diff-df9f9a1870da0e130f5ea66b3de1cda6R825) in node env

**Comment by PaGury** [comment]
Yeah, for nodejs, but for browserify, we are not able to load languages...

**Comment by BenjaminVanRyseghem** [comment]
ok

**Comment by BenjaminVanRyseghem** [comment]
@clayzermk1 do you know?

**Comment by clayzermk1** [comment]
Sorry, I'm only using English. My issue was unrelated.
